spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oopClubManagement?characterEncoding=utf-8
    username: club
    password: 123456

  profiles:
    active: dev

  #  mvc:
#    static-path-pattern: /static/**
  thymeleaf:
    cache: false
#    mode: HTML
#    prefix: classpath:/templates

mybatis:
  mapper-locations: classpath:orm/*.xml
  type-aliases-package: oop.clubsv3.models
